name: acru-l
description: 'ACRU-L configuration execution'
author: 'Quadio'
inputs:
  subcommand:
    description: 'Subcommand to use'
    default: 'deploy -f --require-approval=never'
    required: false
runs:
  using: 'composite'
  steps:
    - run: npm install -g aws-cdk@1.79.0
      shell: bash
    - run: pip install --upgrade pip && pip install acru-l==1.0.0a5
      shell: bash
    - run: acrul ${{ inputs.subcommand }}
      shell: bash
branding:
  icon: arrow-up-circle
  color: gray-dark
